Description of compress_structure
Home > PS_primal_sketch > misc > compress_structure.m
compress_structure
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
PS0z1__settings_sketch settings_sketch_in = PS0z1__settings_sketch(input_image,settings_sketch_in)
PS0z2__settings_tokens settings_tokens_out = PS0z2__settings_tokens(input_image,settings_tokens_in,settings_sketch)
PS1z2__get_gaussian_jet [gauss_jet] = PS1z2__get_gaussian_jet(input_image,scale_gauss,use_iir)
PSLz2a_get_relatives [successors,predecessors,current] = PSLz3_get_neighbors(points,imsize)
PSLz2c_find_connected_curves string_structure = PSLz2c_find_connected_curves(current,succ,pred)
PSLz3a_break_into_lines res = PSLz3a_break_into_lines(components,size_m,size_n,ener)
PSLz3b_embed_lines line_features = PSLz3b_embed_lines(line_parsing,thresh_line_ener)
SOURCE CODE
clear structure
for k_structure=1:length(fields_wt),
    eval(sprintf('structure.%s = %s;',fields_wt{k_structure},fields_wt{k_structure}));
end