Description of pow_2
Home > PS_primal_sketch > misc > pow_2.m
pow_2
PURPOSE
SYNOPSIS
function res = pow_2(input);
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
PS1z3__get_feature_strength [feat_strength_selection,feat_saliency,sc_min,zc] = PS1z3__get_feature_strength(gauss_jet,scale_gauss,feat_tp,settings_sketch)
PS1z3a_get_hessian_orientation [cos_hessian,sin_hessian,L_pp,L_qq] = PS1z3a_get_hessian_orientation(d_xx,d_yy,d_xy)
PS1z4__add_new_points points = PS1z4__add_new_points(points,gauss_jet,indexes,feat_tp,scale_gauss,feat_strength_detection_p,sc_ind)
PSLz3b_embed_lines line_features = PSLz3b_embed_lines(line_parsing,thresh_line_ener)
SOURCE CODE
function res = pow_2(input);
res = input.*input;