Description of demo2
Home > PS_primal_sketch > demo2.m
demo2
PURPOSE
% Shows how to override the standard settings
SYNOPSIS
This is a script file.
DESCRIPTION
% Shows how to override the standard settings
% for primal sketch computation.
% Defaults are in PS0z1_settings_sketch and PS0z2_settings_tokens
%
% Iasonas Kokkinos <jkokkin@stat.ucla.edu>
CROSS-REFERENCE INFORMATION
This function calls:
PS00___primal_sketch [ridge_feats,edge_feats,blob_feats,contours,conn_components,scale_space_ims] = PS00___primal_sketch(input_image,settings_sketch,settings_tests)
show_edges_on_image
show_ellipses_on_image
show_ridges_on_image
This function is called by:
SOURCE CODE
%% Shows how to override the standard settings
%% for primal sketch computation.
%% Defaults are in PS0z1_settings_sketch and PS0z2_settings_tokens
%%
%% Iasonas Kokkinos <jkokkin@stat.ucla.edu>
input_image = double(imread('horse010.jpg'))/256;
%% override defaults for primal sketch extraction
override_sketch.nscales             = 30;
override_sketch.linear_spacing      = 0;     % require geometrical spacing
override_sketch.min_scale           = .3;
%% override defaults for criteria used to select token subset
override_tests.ener_blob_threshold = .2;
override_tests.ener_edge_threshold = .1;
input_image = double(imread('horse010.jpg'))/256;
[ridges,edges,blobs,contours] = PS00___primal_sketch(input_image,override_sketch,override_tests);
%% show sketch tokens
figure,
subplot(2,2,1); show_ridges_on_image(input_image,ridges); title('Ridges')
subplot(2,2,2); show_edges_on_image(input_image,edges);   title('Edges');
subplot(2,2,3); show_ellipses_on_image(input_image,blobs);title('Blobs')
subplot(2,2,4); imshow(colored_sketch); title('Ridge and Edge contours');