Description of demo3
Home > PS_primal_sketch > demo3.m
demo3
PURPOSE
% A demonstration of the intermediate
SYNOPSIS
This is a script file.
DESCRIPTION
% A demonstration of the intermediate
% results used for primal sketch computation
% Shows: scale space construction, maxima locations, curve segments,
% marker image generation.
%
% Iasonas Kokkinos <jkokkin@stat.ucla.edu>
CROSS-REFERENCE INFORMATION
This function calls:
PS00___primal_sketch [ridge_feats,edge_feats,blob_feats,contours,conn_components,scale_space_ims] = PS00___primal_sketch(input_image,settings_sketch,settings_tests)
PSzz_components_to_markers [ridge_markers] = PSzz_components_to_markers(ridge_components,input_image)
PSzz_unzip_contour [res,orn] = PSzz_unzip_skeleton(skeleton)
colored_contours
show_3d_volume mov_volume = show_3d_volume(val_3d_array,step);
show_edges_on_image
show_intermediate_curves_on_image
show_ridges_on_image
This function is called by:
SOURCE CODE
%% A demonstration of the intermediate
%% results used for primal sketch computation
%% Shows: scale space construction, maxima locations, curve segments,
%% marker image generation.
%%
%% Iasonas Kokkinos <jkokkin@stat.ucla.edu>
input_image = double(imread('horse010.jpg'))/256;
%% Request the cubes formed by the intensity and feature-strength images
%% as the scale increases. Binary entries, corresponding to (ridge, edge, blob, intensity)
override_sketch.keep_scale_space_im = [1,1,0,1];
override_tests  = [];
[ridges,edges,blobs,contours,connected_components,scale_space_ims] =...
            PS00___primal_sketch(input_image,override_sketch,override_tests);
for it =[1,2],
    if it==1,
        tokens = ridges; color = 'b';
        location_maxima       = PSzz_unzip_contour(contours{1});
        colored_sketch      =  colored_contours(input_image,location_maxima,zeros(size(input_image)));
    else
        tokens = edges; color = 'g';
        location_maxima       = PSzz_unzip_contour(contours{2});
        colored_sketch      =  colored_contours(input_image,zeros(size(input_image)),location_maxima);
    end
    %% Visualize feature strength-versus-scale as a cube.
    figure,show_3d_volume(scale_space_ims{it});
    %% Show the 3 processing stages involved in token computation
    figure,
    subplot(1,3,1);
    imshow(colored_sketch);
    title('Maxima Locations');
    subplot(1,3,2);
    show_intermediate_curves_on_image(input_image,tokens,color);
    title('Curve Segments');
    subplot(1,3,3);
    if it==1,
        show_ridges_on_image(input_image,tokens);
    else
        show_edges_on_image(input_image,tokens);
    end
    title('Straight tokens');
end
[ridge_markers] = PSzz_components_to_markers(connected_components{1},input_image);
figure,imshow(min(input_image,1-ridge_markers)); title('Ridge markers superimposed on image');